sonar.projectKey=osaro-tech-store-backend
sonar.projectName=Osaro Tech Store Backend
sonar.projectVersion=2.0.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,coverage/**,tests/coverage/**
sonar.coverage.exclusions=src/server.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
