export const HTTP_STATUS_BY_ERROR_CODE = Object.freeze({
  VALIDATION: 400,
  INVALID_INPUT: 400,

  UNAUTHORIZED: 401,

  FORBIDDEN: 403,

  NOT_FOUND: 404,

  CONFLICT: 409,

  SERVICE_UNAVAILABLE: 503,
});

export const DEFAULT_HTTP_STATUS = 500;
